/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        rpg: {
          bg: '#1a120b',
          surface: '#2a1f14',
          panel: '#342618',
          border: '#5c3d1e',
          borderlite: '#8b6914',
          gold: '#d4a540',
          'gold-dark': '#a07830',
          hp: '#c93030',
          'hp-dark': '#8b1a1a',
          mana: '#4a7fd4',
          'mana-dark': '#2a5ca0',
          green: '#4a9e5c',
          purple: '#8a5cb8',
          text: '#d8ccb4',
          muted: '#8a7a60',
          crimson: '#a02040',
          navy: '#1a1a30',
          amber: '#c89020',
        },
        grimoire: {
          parchment: '#c8b88a',
          'parchment-dark': '#a89060',
          ink: '#2a1a0a',
          'ink-light': '#4a3a2a',
          leather: '#3a2010',
          'leather-light': '#5a3820',
          spine: '#2a1508',
          clasp: '#b8942a',
          ribbon: '#8b1a1a',
          rune: '#d4a540',
          'page-edge': '#e8d8b8',
        },
      },
      fontFamily: {
        pixel: ['"Press Start 2P"', 'monospace'],
        body: ['"VT323"', 'monospace'],
        grimoire: ['"MedievalSharp"', 'cursive'],
        fraktur: ['"UnifrakturMaguntia"', 'cursive'],
      },
      fontSize: {
        'pixel-xs': ['8px', { lineHeight: '1.8' }],
        'pixel-sm': ['10px', { lineHeight: '1.8' }],
        'pixel-base': ['12px', { lineHeight: '1.8' }],
        'pixel-lg': ['14px', { lineHeight: '1.8' }],
        'pixel-xl': ['16px', { lineHeight: '1.8' }],
        'pixel-2xl': ['20px', { lineHeight: '1.6' }],
        'body-sm': ['16px', { lineHeight: '1.4' }],
        'body-base': ['18px', { lineHeight: '1.4' }],
        'body-lg': ['22px', { lineHeight: '1.4' }],
        'body-xl': ['28px', { lineHeight: '1.3' }],
        'grimoire-sm': ['14px', { lineHeight: '1.4' }],
        'grimoire-base': ['16px', { lineHeight: '1.4' }],
        'grimoire-lg': ['24px', { lineHeight: '1.3' }],
        'grimoire-xl': ['32px', { lineHeight: '1.2' }],
      },
      boxShadow: {
        pixel: '4px 4px 0px rgba(0,0,0,0.6)',
        'pixel-sm': '2px 2px 0px rgba(0,0,0,0.6)',
        'pixel-panel':
          'inset -3px -3px 0px #0a0a1a, inset 3px 3px 0px #3a3a7e, 0 0 0 3px #1a1a3e, 0 0 0 5px #0a0a1a',
        'pixel-btn': '4px 4px 0px rgba(0,0,0,0.7)',
        'pixel-inset': 'inset 2px 2px 0px rgba(0,0,0,0.5)',
        'grimoire-page': 'inset 0 0 30px rgba(0,0,0,0.15), 0 2px 8px rgba(0,0,0,0.3)',
        'grimoire-inset': 'inset 2px 2px 4px rgba(0,0,0,0.3), inset -1px -1px 2px rgba(255,255,255,0.05)',
      },
      animation: {
        'ko-flash': 'koFlash 0.4s steps(1) infinite',
        'blink': 'blink 1s steps(1) infinite',
        'breathe': 'breathe 3s ease-in-out infinite',
        'idle-bob': 'idleBob 2s ease-in-out infinite',
        'flame-flicker': 'flameFlicker 0.3s ease-in-out infinite alternate',
        'rune-glow': 'runeGlow 2s ease-in-out infinite',
      },
      keyframes: {
        koFlash: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        breathe: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.02)' },
        },
        idleBob: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-2px)' },
        },
        flameFlicker: {
          '0%': { opacity: '0.8', transform: 'scaleY(1)' },
          '100%': { opacity: '1', transform: 'scaleY(1.1)' },
        },
        runeGlow: {
          '0%, 100%': { filter: 'brightness(1) drop-shadow(0 0 2px rgba(212,165,64,0.3))' },
          '50%': { filter: 'brightness(1.3) drop-shadow(0 0 6px rgba(212,165,64,0.6))' },
        },
      },
    },
  },
  plugins: [],
}
